### ISSUE TITLE
Validation errors appear as Marshmallow Exceptions and don't get raised as http errors

### ISSUE THREAD

**Issue by alienhaxor** [ihiji/falcon-marshmallow#15]
When doing a POST with invalid data I get a

```
HTTP/1.1 200 OK
Connection: keep-alive
Content-Encoding: gzip
Content-Type: application/json; charset=UTF-8
Date: Tue, 12 Dec 2017 20:34:35 GMT
Keep-Alive: timeout=10
Server: nginx
Strict-Transport-Security: max-age=31536000
Transfer-Encoding: chunked
Vary: Accept-Encoding
X-Content-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block

{
    "error": {
        "code": 500,
        "msg": "Something went wrong"
    }
}

```

And the internal server error is

```
web_1    | [2017-12-12 20:34:35,370 controlpanel.server ERROR 1fe9260230bb8a7db417be6bb2c15cdc] {'user_script': ['Missing data for required field.'], 'title': ['Missing data for required field.']}
web_1    | Traceback (most recent call last):
web_1    |   File "/usr/local/lib/python3.6/site-packages/falcon/api.py", line 240, in __call__
web_1    |     process_resource(req, resp, resource, params)
web_1    |   File "/usr/local/lib/python3.6/site-packages/falcon_marshmallow/middleware.py", line 300, in process_resource
web_1    |     data, errors = sch.load(parsed)
web_1    |   File "/usr/local/lib/python3.6/site-packages/marshmallow/schema.py", line 580, in load
web_1    |     result, errors = self._do_load(data, many, partial=partial, postprocess=True)
web_1    |   File "/usr/local/lib/python3.6/site-packages/marshmallow/schema.py", line 701, in _do_load
web_1    |     raise exc
web_1    | marshmallow.exceptions.ValidationError: {'user_script': ['Missing data for required field.'], 'title': ['Missing data for required field.']}
web_1    | [2017-12-12 20:34:35,377 SERVER INFO 1fe9260230bb8a7db417be6bb2c15cdc] END POST /v1/user-scripts
web_1    | [pid: 8|app: 0|req: 1/1] 172.21.0.4 () {46 vars in 801 bytes} [Tue Dec 12 20:34:35 2017] POST /v1/user-scripts => generated 55 bytes in 53 msecs (HTTP/1.0 200) 2 headers in 86 bytes (1 switches on core 0)
```

But the documentation says this should happen:

"When parsing a request body, if it cannot be decoded or its JSON is malformed, an HTTPBadRequest error will be raised. If the deserialization of the request body fails due to schema validation errors, an HTTPUnprocessableEntity error will be raised."

What am I doing wrong?

**Comment by mplanchard** [comment]
Hi there! Thanks for raising an issue. To start, could you show us the schema that's being loaded? 

My first guess is that the issue may be due to your schema being set to "strict", which results in errors being raised directly rather than stored in the `errors` dict during schema processing.

**Comment by alienhaxor** [comment]
Thanks for the quick reply!

My Schema:

```
class Post_UserScript(Schema):
    class Meta:
        strict = True

    title = fields.Str(required=True)
    user_script = fields.Str(required=True)
```

I removed

```
class Meta:
    strict = True
```

And when POSTing invalid JSON I get HTTPUnprocessableEntity.

If I do a post without JSON body I get an error:

```
web_1    | [2017-12-13 10:08:40,945 SERVER INFO d8194fc4e97a1b3cac4c4450c889a172] START POST /v1/user-scripts
web_1    | [2017-12-13 10:08:40,945 controlpanel.server ERROR d8194fc4e97a1b3cac4c4450c889a172] ** Exception raised **
web_1    | [2017-12-13 10:08:40,945 controlpanel.server ERROR d8194fc4e97a1b3cac4c4450c889a172] 'json'
web_1    | Traceback (most recent call last):
web_1    |   File "/usr/local/lib/python3.6/site-packages/falcon/api.py", line 242, in __call__
web_1    |     responder(req, resp, **params)
web_1    |   File "./controlpanel/api/v1/user_scripts.py", line 45, in on_post
web_1    |     inserted = repo.add(main_account_id, req.context['json'])
web_1    | KeyError: 'json'
```

Shouldn't this trigger a bad request invalid JSON kind of error?

**Comment by mplanchard** [comment]
We don't raise an error on a request with no JSON body and a content length of zero. We simply drop it. See the following block for details:

https://github.com/ihiji/falcon-marshmallow/blob/5aa4276b425ea24204830f9ec46b29b5875d822b/falcon_marshmallow/middleware.py#L105-L130

We do raise an error if the request has a content length and no content, though.

The reasoning for this is that technically an empty request is not an invalid request. There are definitely non-ReSTful services out there that treat an empty POST to a given endpoint as a trigger for some kind of action.

**Comment by mplanchard** [comment]
Addendum: other, more obvious examples of places where you wouldn't want to drop a request just because it has an empty body are GET requests, OPTIONS requests, and HEAD requests.

**Comment by alienhaxor** [comment]
Thanks for the comprehensive responses. This issue is resolved for me. Have a good day!

**Comment by mplanchard** [comment]
You, too, @cancerballs!
