### ISSUE TITLE
callable get_schema?

### ISSUE THREAD

**Issue by timc13** [ihiji/falcon-marshmallow#17]
Have you considered changing the API to expose a `get_schema` callable so you could return different schema instances dynamically?  This would be useful, for example, if someone had different users permissioned for different things accessing the same endpoint.  You might want to use different schemas depending on their permissions.

**Comment by timc13** [comment]
by the way, I've gotten around this for response objects by setting `self.schema` but there's no way to set the schema for request objects

**Comment by jfpoilpret** [comment]
Another rather common use case would be to return error details in response as JSON body (in addition to HTTP status code). 
The resource object would by default use resource schema for situations that work normally (HTTP 200), but the handlers might change it to an "ErrorSchema" in case an error happened.

**Comment by mplanchard** [comment]
Hey y'all. Sorry I missed the notifications on this issue. I moved on from Ihiji in January, and I had all Ihiji repos set up to go to to my old work e-mail.

I like this idea, and I'm happy to work on implementing it. Are we envisioning the `get_schema` callable to be like an entrypoint for a global schema registry? Or would it just be getting schemas already associated with the class?

**Comment by timc13** [comment]
I think flexibility is key here.  For my use case, I need to return different instances of the schema depending on the user type.

For example: admin users could get `FooSchema()`, but a regular user could get `FooSchema(exclude='secret_field')`

**Comment by mplanchard** [comment]
Given the relative abandonment of the project here, please let's continue discussion at mplanchard/falcon-marshmallow#1
